#!/bin/bash

cd "$(dirname "$0")"
read -p "Please enter commit message here:" cmtmsg
git add .
git commit -m "Update $(date '+%Y-%m-%d %H:%M:%S'): $cmtmsg"
git push origin main  # or gh-pages, if that’s your deploy branch

